name: Test build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Check
      run: bundle exec checklinks --config .checklinks.yaml **.md
    - name: Build
      run: bundle exec jekyll build
