name: Test build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf
    - name: Install Ruby
      uses: eregon/use-ruby-action@108b3a2c8a79ce6a8b5402c2f7d242009737bdf0
    - name: Install
      run: bundle install
    - name: Build
      run: bundle exec jekyll build
    - name: Check
      run: bundle exec checklinks --config .checklinks.yaml **.md
